name: Game-CI Unity Build 🎮
on:
  workflow_call:
    inputs:
      BUILD_TARGET:
        description: 'Unity build target platform'
        default: Android
        required: true
        type: string

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #UNITY_VERSION: 2021.4.10f1

jobs:
  build:
    name: Building for ${{ inputs.BUILD_TARGET }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
  
      - name: cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ inputs.BUILD_TARGET }}
          restore-keys: Library-

      - name: Set timestamp
        run: echo "TIME_STAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Set Artifact name
        run: echo "ARTIFACT_NAME=${{ github.event.repository.name }}-${{ inputs.BUILD_TARGET }}-${{ env.TIME_STAMP }}" >> $GITHUB_ENV

      # - name: Rename artifact
      #   run: echo "ARTIFACT_NAME=${{ env.ARTIFACT_NAME }}.txt" >> $GITHUB_ENV
      # - name: Generate dummy artifact
      #   run: echo "Hello World!" > "${{ env.ARTIFACT_NAME }}"

      - name: Unity Build using Game CI
        uses: game-ci/unity-builder@v2.1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
         # email and pwd only required for pro license
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ inputs.BUILD_TARGET }}
          allowDirtyBuild: true
          versioning: Semantic
          #unityVersion: ${{ env.UNITY_VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build

      - name: Echo URL
        run: echo "https://github.com/$GITHUB_REPOSITORY/actions/downloads/${{ env.ARTIFACT_NAME }}"
    
    # teams notification
      - name: Set artifact URL
        id: set-artifact-url
        run: echo "artifacturl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
      - name: Test artifact URL
        run: echo "The artifact URL is ${{ steps.set-artifact-url.outputs.artifacturl }}"
      
    outputs:
      artifacturl: ${{ steps.set-artifact-url.outputs.artifacturl }}
  
  notify-teams:
    needs: build
    uses: ./.github/workflows/ms-teams-notification.yml
    secrets: inherit
    with:
      artifact_url: ${{ needs.build.outputs.artifacturl }}