name: 2. Check Unity License ☑️
on: [workflow_call, workflow_dispatch]

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
   CheckUnityLicense:
       name: Check Unity License
       runs-on: ubuntu-latest
       steps:
         - name: Fail - No license ☠️
           if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
           run: exit 1
