name: Android Build 📱
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target_branch:
        description: workflow host branch
        type: string
        default: main
        required: true
        
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  ARTIFACT_NAME: dummy
  ARTIFACT_EXT: apk
  
jobs:
  AndroidBuild:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Test target branch
        run: echo target branch is ${{ inputs.target_branch }}    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
           ref: ${{ inputs.target_branch }}        

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-build-Android
          restore-keys: |
            Library-build-
            Library-

      - uses: webbertakken/unity-builder@v2
        with:
          targetPlatform: Android
          #unityVersion: 2020.3.2f1
          allowDirtyBuild: true

      - name: Set TIME_STAMP
        run: echo "TIME_STAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Set ARTIFACT_NAME & vars
        run: echo "ARTIFACT_NAME=${{ env.ARTIFACT_NAME }}-${{ env.TIME_STAMP }}" >> $GITHUB_ENV
      - name: Set ARTIFACT_FILE
        run: echo "ARTIFACT_FILE=${{ env.ARTIFACT_NAME }}.${{ env.ARTIFACT_EXT }}" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_FILE }}

    # teams notification
      - name: Set artifact URL
        id: set-artifact-url
        run: echo "artifacturl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
      - name: Test artifact URL
        run: echo "The artifact URL is ${{ steps.set-artifact-url.outputs.artifacturl }}"
      
    outputs:
      artifacturl: ${{ steps.set-artifact-url.outputs.artifacturl }}
  
  notify-teams:
    needs: AndroidBuild
    uses: ./.github/workflows/ms-teams-notification.yml
    secrets: inherit
    with:
      artifact_url: ${{ needs.generate-artifact.outputs.artifacturl }}