name: Generate UML Diagrams

on:
  push:
    paths:
      - 'docs/diagrams/*.puml'
jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Diagrams using PlantUML Docker image
      run: docker run --rm -v $(pwd):/plantuml plantuml/plantuml -o /plantuml/docs/diagrams /plantuml/docs/diagrams/*.puml

    - name: Commit and Push Diagrams
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git add -A
        git commit -m "Generate UML diagrams" || echo "No changes to commit"
        git push origin || echo "No changes to push"