name: input sender
on: 
  workflow_dispatch:

env:
  username: bob

jobs:
  test-username:
    runs-on: ubuntu-latest
    outputs:
      somevar: ${{ steps.step1.outputs.username }}

    steps:
      - name: set output
        id: step1
        run: echo "username=$GITHUB_ACTOR" >> $GITHUB_OUTPUT

  send-username:
    name: call input-receiver
    needs: test-username
    uses: ./.github/workflows/input-receiver.yml
    with:
      username: ${{ needs.test-username.outputs.somevar }}