name: input receiver
on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john doe'
        required: true
        type: string

env:
  platform: win64

jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input name to STDOUT
        run: echo username ${{ inputs.username }}